name: BRAHMAAX Cloud Recorder

on:
  schedule:
    - cron: "*/1 4-10 * * 1-5"
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run recorder
        run: run: python recorder.py

      - name: Commit candle data
        run: |
          git config --global user.name "brahmaax-cloud"
          git config --global user.email "cloud@brahmaax.ai"
          git add database/brahmaax_candles.csv
          git commit -m "Cloud candle update" || echo "No changes"
          git push
